const InitialBoardObject = {
  "H8": ["tower", "black"],
  "G8": ["horse", "black"],
  "F8": ["bishop", "black"],
  "E8": ["queen", "black"],
  "D8": ["king", "black"],
  "C8": ["bishop", "black"],
  "B8": ["horse", "black"],
  "A8": ["tower", "black"],
  "H7": ["pawn", "black"],
  "G7": ["pawn", "black"],
  "F7": ["pawn", "black"],
  "E7": ["pawn", "black"],
  "D7": ["pawn", "black"],
  "C7": ["pawn", "black"],
  "B7": ["pawn", "black"],
  "A7": ["pawn", "black"],
  "A1": ["tower", "white"],
  "B1": ["horse", "white"],
  "C1": ["bishop", "white"],
  "D1": ["queen", "white"],
  "E1": ["king", "white"],
  "F1": ["bishop", "white"],
  "G1": ["horse", "white"],
  "H1": ["tower", "white"],
  "H2": ["pawn", "white"],
  "G2": ["pawn", "white"],
  "F2": ["pawn", "white"],
  "E2": ["pawn", "white"],
  "D2": ["pawn", "white"],
  "C2": ["pawn", "white"],
  "B2": ["pawn", "white"],
  "A2": ["pawn", "white"],
}

module.exports = InitialBoardObject